### ISSUE TITLE
License

### ISSUE THREAD

**Issue by spco** [AtChem2/AtChem2#243]
We still don't have a license in place. We definitely should.

**Comment by spco** [comment]
@rs028 : In response to your question about MIT vs GPL, it seems that GPL requires any derived software to also use a GPL license, whereas MIT puts no condition on that, merely that the attribution is kept. I think MIT better suits our purposes for this, as we're more concerned with attribution than restricting further use - does that sound ok?

**Comment by rs028** [comment]
Okay. I really don't have strong opinions on that, as long as it is a full open source. If you prefer MIT I'm happy with that. We could put to options to vote to the others indicating our preference.

**Comment by spco** [comment]
Ok, I'll prepare two versions, and a brief description of the two choices. I'll email you before the day is out.

**Comment by spco** [comment]
Closed by #249
