### ISSUE TITLE
Copyright/credit

### ISSUE THREAD

**Issue by spco** [AtChem2/AtChem2#246]
Ideally all files should have a copyright/credit section in the header, which gives a few details of who wrote it and when.

This is made trickier by the fact that large amounts of the code was written beforehand, and we may not be able to trace who did what. Perhaps we then go down the route of adding all names to all the files, unless they are explicitly new (such as `parameterModules.f90`, and perhaps `solarFunctions.f90`/ `atmosphereFunctions.f90` given how almost all the functions have been re-written). In particular, the build and test systems are all our own work, so that should have a header stating such. 

This all helps to identify who did what later!

**Comment by spco** [comment]
The usual convention is to add authors as they touch individual files, and to update the copyright year each time a file is edited.

**Comment by rs028** [comment]
@spco, apart from copyright, credits, licence is there something else or are you done with all we talked about?

**Comment by spco** [comment]
I think that's everything on my list! Once the license is in place, from my POV we are good for a release version.

**Comment by spco** [comment]
Closed by #249
